import { Router, Request, Response, NextFunction } from 'express';
import { ChatbotController } from './controllers/chatbot.controller';
import { chatbotSessionMiddleware } from './middlewares/session.middleware';
import jwt from 'jsonwebtoken';
import { env } from '../../config/env.config';
import { User } from '../auth-account/models/user.model';

const router = Router();

// Middleware to optionally authenticate user if token is provided
const optionalAuthenticateJWT = async (req: Request, res: Response, next: NextFunction) => {
  const authHeader = req.headers.authorization;
  if (authHeader && authHeader.startsWith('Bearer ')) {
    const token = authHeader.split(' ')[1];
    try {
      const decoded = jwt.verify(token, env.JWT_SECRET) as any;
      const user = await User.findById(decoded.userId);
      if (user) {
        req.user = user;
      }
    } catch (err) {
      // Ignore errors for optional auth
    }
  }
  next();
};

/**
 * @openapi
 * tags:
 *   name: Chatbot
 *   description: AI Chatbot API endpoints
 * 
 * /api/v1/chatbot/message:
 *   post:
 *     summary: Send a message to the AI Chatbot
 *     description: Send a message to the AI Chatbot. The response is streamed back using Server-Sent Events (SSE). If the `clientRequestId` matches an existing processing request, it returns the existing response.
 *     tags: [Chatbot]
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [message, clientRequestId]
 *             properties:
 *               message:
 *                 type: string
 *                 description: The text message from the user
 *                 example: "Tôi muốn hiến máu thì cần điều kiện gì?"
 *               clientRequestId:
 *                 type: string
 *                 description: A unique ID generated by the client to ensure idempotency
 *                 example: "req-123456789"
 *     responses:
 *       200:
 *         description: Successful stream of AI response (Server-Sent Events) or JSON response if already processed
 *         content:
 *           text/event-stream:
 *             schema:
 *               type: string
 *               example: 'data: {"text": "Chào bạn, "}\n\n'
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 status:
 *                   type: string
 *                   example: "success"
 *                 data:
 *                   type: object
 *                   properties:
 *                     message:
 *                       type: object
 *                       description: The cached AI message object
 *                     conversationId:
 *                       type: string
 *       400:
 *         description: Bad Request (missing required fields)
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 error:
 *                   type: string
 *                   example: "Message and clientRequestId are required"
 *       500:
 *         description: Internal Server Error
 *       503:
 *         description: AI Service Unavailable
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 error:
 *                   type: string
 *                   example: "AI service is temporarily unavailable. Please try again shortly."
 */
router.post('/message', optionalAuthenticateJWT, chatbotSessionMiddleware, ChatbotController.sendMessage);

/**
 * @openapi
 * /api/v1/chatbot/history:
 *   get:
 *     summary: Get conversation history
 *     description: Retrieves the chat history of the most recent conversation for the current session or authenticated user.
 *     tags: [Chatbot]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: query
 *         name: page
 *         schema:
 *           type: integer
 *           default: 1
 *         description: Page number for pagination
 *       - in: query
 *         name: limit
 *         schema:
 *           type: integer
 *           default: 20
 *         description: Number of messages to retrieve per page
 *     responses:
 *       200:
 *         description: Successfully retrieved history
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 status:
 *                   type: string
 *                   example: "success"
 *                 data:
 *                   type: object
 *                   properties:
 *                     messages:
 *                       type: array
 *                       items:
 *                         type: object
 *                         properties:
 *                           _id:
 *                             type: string
 *                           sender:
 *                             type: string
 *                             enum: [User, AI]
 *                           contentText:
 *                             type: string
 *                           sentAt:
 *                             type: string
 *                             format: date-time
 *                     conversationId:
 *                       type: string
 *                       nullable: true
 *                     status:
 *                       type: string
 *                       example: "active"
 *       500:
 *         description: Internal Server Error
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 error:
 *                   type: string
 *                   example: "Internal server error retrieving history"
 */
router.get('/history', optionalAuthenticateJWT, chatbotSessionMiddleware, ChatbotController.getHistory);

export default router;
